name: servant-yaml
version: 0.1.0.0
synopsis: Servant support for yaml
description: Servant support for yaml
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/servant-yaml
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base        >=4.7      && <4.9
  - bytestring  >=0.10.4.0 && <0.11
  - http-media  >=0.6.2    && <0.7
  - servant     >=0.4.4.5  && <0.8
  - yaml        >=0.8.12   && <0.9

library:
  source-dirs: src

tests:
  example:
    main: Main.hs
    source-dirs: example
    dependencies:
      - servant-yaml
      - servant-server >=0.4.4.5  && <0.8
      - base-compat    >=0.6.0    && <0.10
      - aeson          >=0.8.0.2  && <0.12
      - wai            >=3.0.3.0  && <3.3
      - warp           >=3.0.13.1 && <3.3
